export const enum RankStrength { 
	ROYAL_STRAIGHT_FLUSH = 10,
	STRAIGHT_FLUSH = 9,
	STRONG_RANK = 8.1,
	FOUR_CARD = 8,
	FULL_HOUSE = 7,
	FLUSH  = 6,
	STRAIGHT  = 5,
	HIGH_THREE_CARD = 4.3,
	MIDDLE_THREE_CARD = 4.2,
	LOW_THREE_CARD = 4.1,
	THREE_CARD = 4,
	HIGH_TWO_PAIR = 3.3,
	MIDDLE_TWO_PAIR = 3.2,
	TWO_PAIR_TOP  = 3.15,
	LOW_TWO_PAIR = 3.1,
	TWO_PAIR  = 3,
	ONE_PAIR_A  = 2.7,
	ONE_PAIR_K  = 2.6,
	ONE_PAIR_Q  = 2.5,
	ONE_PAIR_TOP  = 2.45,
	ONE_PAIR_MIDDLE  = 2.2,
	ONE_PAIR_LOW  = 2.1,
	ONE_PAIR  = 2,
	NO_PAIR_A  = 1.7,
	NO_PAIR_K  = 1.6,
	NO_PAIR_Q  = 1.5,
	NO_PAIR_HIGH  = 1.45,
	NO_PAIR_MIDDLE  = 1.2,
	NO_PAIR_LOW  = 1.1,
	NO_PAIR  = 1
}
export const ALL_REAL_RANK_STRENGTH = [
	RankStrength.STRAIGHT_FLUSH,
	RankStrength.FOUR_CARD,
	RankStrength.FULL_HOUSE,
	RankStrength.FLUSH,
	RankStrength.STRAIGHT,
	RankStrength.HIGH_THREE_CARD,
	RankStrength.MIDDLE_THREE_CARD,
	RankStrength.LOW_THREE_CARD,
	RankStrength.HIGH_TWO_PAIR,
	RankStrength.MIDDLE_TWO_PAIR,
	RankStrength.LOW_TWO_PAIR,
	RankStrength.ONE_PAIR_A,
	RankStrength.ONE_PAIR_K,
	RankStrength.ONE_PAIR_Q,
	RankStrength.ONE_PAIR_MIDDLE,
	RankStrength.ONE_PAIR_LOW,
	RankStrength.NO_PAIR_A,
	RankStrength.NO_PAIR_K,
	RankStrength.NO_PAIR_Q,
	RankStrength.NO_PAIR_MIDDLE,
	RankStrength.NO_PAIR_LOW
];
export const ALL_REAL_RANK_STRENGTH_FOR_MIDSTREAM = [
	RankStrength.STRONG_RANK,
	RankStrength.FULL_HOUSE,
	RankStrength.FLUSH,
	RankStrength.STRAIGHT,
	RankStrength.THREE_CARD,
	RankStrength.TWO_PAIR_TOP,
	RankStrength.TWO_PAIR,
	RankStrength.ONE_PAIR_TOP,
	RankStrength.ONE_PAIR,
	RankStrength.NO_PAIR_HIGH,
	RankStrength.NO_PAIR
];
